package app.simple.positional.constants

import android.graphics.Color
import app.simple.positional.R

object LauncherBackground {
    val vectorBackground = intArrayOf(
            R.drawable.launcher_day_01,
            R.drawable.launcher_day_02,
            R.drawable.launcher_day_03,
            R.drawable.launcher_day_04,
            R.drawable.launcher_day_05,
            R.drawable.launcher_day_06,
            R.drawable.launcher_day_07,
            R.drawable.launcher_day_08,
            R.drawable.launcher_day_09,
            R.drawable.launcher_day_10,
            R.drawable.launcher_day_11,
            R.drawable.launcher_day_12,
            R.drawable.launcher_day_13,
            R.drawable.launcher_day_14,
            R.drawable.launcher_day_15,
            R.drawable.launcher_day_16,
            R.drawable.launcher_day_17,
            R.drawable.launcher_day_18,
            R.drawable.launcher_day_19,
            R.drawable.launcher_day_20,
            R.drawable.launcher_day_21,
            R.drawable.launcher_day_22,
            R.drawable.launcher_day_23,
            R.drawable.launcher_day_24,
            R.drawable.launcher_day_25,
            R.drawable.launcher_day_26,
            R.drawable.launcher_day_27,
            R.drawable.launcher_day_28,
            R.drawable.launcher_day_29,
            R.drawable.launcher_day_30,
            R.drawable.launcher_day_31,
            R.drawable.launcher_day_32,
            R.drawable.launcher_day_33,
            R.drawable.launcher_day_34,
            R.drawable.launcher_day_35,
            R.drawable.launcher_day_36,
            R.drawable.launcher_day_37,
            R.drawable.launcher_day_38,
            R.drawable.launcher_day_39,
            R.drawable.launcher_day_40,
            R.drawable.launcher_day_41,
            R.drawable.launcher_day_42,
            R.drawable.launcher_day_43,
            R.drawable.launcher_day_44,
            R.drawable.launcher_day_45,
            R.drawable.launcher_day_46,
            R.drawable.launcher_day_47,
            R.drawable.launcher_day_48,
            R.drawable.launcher_day_49,
            R.drawable.launcher_day_50,
            R.drawable.launcher_day_51,
            R.drawable.launcher_day_52,
            R.drawable.launcher_day_53,
            R.drawable.launcher_day_54
    )

    val vectorBackgroundNight = intArrayOf(
            R.drawable.launcher_night_01,
            R.drawable.launcher_night_02,
            R.drawable.launcher_night_03,
            R.drawable.launcher_night_04,
            R.drawable.launcher_night_05,
            R.drawable.launcher_night_06,
            R.drawable.launcher_night_07,
            R.drawable.launcher_night_08,
            R.drawable.launcher_night_09,
            R.drawable.launcher_night_10,
            R.drawable.launcher_night_11,
            R.drawable.launcher_night_12,
            R.drawable.launcher_night_13,
            R.drawable.launcher_night_14,
            R.drawable.launcher_night_15
    )

    val vectorColors: Array<IntArray> = arrayOf(
            intArrayOf(parseColor("#FFF6E58D"), parseColor("#FFE056FD")),
            intArrayOf(parseColor("#FFFFD71D"), parseColor("#FF804700")),
            intArrayOf(parseColor("#FFaa8659"), parseColor("#FFaa8659")),
            intArrayOf(parseColor("#FF9d56a0"), parseColor("#FF246887")),
            intArrayOf(parseColor("#FFDE542A"), parseColor("#FFBA2D0A")),
            intArrayOf(parseColor("#FF52618c"), parseColor("#FF6b8ea9")),
            intArrayOf(parseColor("#FF434E94"), parseColor("#FF081146")),
            intArrayOf(parseColor("#FFDE7E42"), parseColor("#FFBF5047")),
            intArrayOf(parseColor("#FF246887"), parseColor("#FF247ca7")),
            intArrayOf(parseColor("#FFff7841"), parseColor("#FFf14f2a")),
            intArrayOf(parseColor("#FF596869"), parseColor("#FFa9a094")),
            intArrayOf(parseColor("#FFC2602A"), parseColor("#FFE89144")),
            intArrayOf(parseColor("#FFFC6F55"), parseColor("#FFC3687B")),
            intArrayOf(parseColor("#FF69525E"), parseColor("#FF432131")),
            intArrayOf(parseColor("#FF441F00"), parseColor("#FFBE804C")),
            intArrayOf(parseColor("#FF871E67"), parseColor("#FF4a0a32")),
            intArrayOf(parseColor("#FFFF8A9F"), parseColor("#FFB6577C")),
            intArrayOf(parseColor("#FFffe8c7"), parseColor("#FFf5c579")),
            intArrayOf(parseColor("#FF91AEAD"), parseColor("#FF2f4a5d")),
            intArrayOf(parseColor("#FF008D7D"), parseColor("#FF1e0b53")),
            intArrayOf(parseColor("#FF872133"), parseColor("#FFBB4657")),
            intArrayOf(parseColor("#FF44408D"), parseColor("#FF1C7EB6")),
            intArrayOf(parseColor("#FF9F38AA"), parseColor("#FF541A5A")),
            intArrayOf(parseColor("#FFEBAC59"), parseColor("#FF9C314C")),
            intArrayOf(parseColor("#FF00748e"), parseColor("#FF004b5b")),
            intArrayOf(parseColor("#FF8D6AA9"), parseColor("#FFBD95C3")),
            intArrayOf(parseColor("#FF48543E"), parseColor("#FFBEA46F")),
            intArrayOf(parseColor("#FFBE4E31"), parseColor("#FF7A3027")),
            intArrayOf(parseColor("#FF912B86"), parseColor("#FF33307F")),
            intArrayOf(parseColor("#FF7b8c62"), parseColor("#FF4b594b")),
            intArrayOf(parseColor("#FFB1606B"), parseColor("#FFF3A464")),
            intArrayOf(parseColor("#FFF27E8B"), parseColor("#FF395175")),
            intArrayOf(parseColor("#FFBC8E6F"), parseColor("#FFE9C49E")),
            intArrayOf(parseColor("#FFa14118"), parseColor("#FFdb6532")),
            intArrayOf(parseColor("#FF1B72A7"), parseColor("#FF1BA0D1")),
            intArrayOf(parseColor("#FFa12c34"), parseColor("#FFF87136")),
            intArrayOf(parseColor("#FF6b4a60"), parseColor("#FFFF8D64")),
            intArrayOf(parseColor("#FF25b782"), parseColor("#FF006f7a")),
            intArrayOf(parseColor("#FF864141"), parseColor("#FFC06790")),
            intArrayOf(parseColor("#FF2d3f43"), parseColor("#FF5c6b4d")),
            intArrayOf(parseColor("#FF9C3F88"), parseColor("#FFBD2E94")),
            intArrayOf(parseColor("#FF129483"), parseColor("#FF3EAF98")),
            intArrayOf(parseColor("#FFFF9266"), parseColor("#FFFFDC78")),
            intArrayOf(parseColor("#FF3d6199"), parseColor("#FFfa7169")),
            intArrayOf(parseColor("#FF28ADD1"), parseColor("#FFFF9F29")),
            intArrayOf(parseColor("#FF0042AE"), parseColor("#FF5BA9FD")),
            intArrayOf(parseColor("#FF0a6d82"), parseColor("#FF5aa7c3")),
            intArrayOf(parseColor("#FF190D46"), parseColor("#FF402287")),
            intArrayOf(parseColor("#FF282A57"), parseColor("#FFDE5654")),
            intArrayOf(parseColor("#FF36A1FF"), parseColor("#FF7DE5FF")),
            intArrayOf(parseColor("#FFbe5c35"), parseColor("#FFeabc83")),
            intArrayOf(parseColor("#FFcd4416"), parseColor("#FFd56735")),
            intArrayOf(parseColor("#FF008CA2"), parseColor("#FF00C8CA")),
            intArrayOf(parseColor("#FF0085bb"), parseColor("#FF66d9db")),
    )

    val vectorNightColors: Array<IntArray> = arrayOf(
            intArrayOf(parseColor("#FFffa32a"), parseColor("#FFcb555b")),
            intArrayOf(parseColor("#FFd34f59"), parseColor("#FFc65464")),
            intArrayOf(parseColor("#FF4c355e"), parseColor("#FF311b3f")),
            intArrayOf(parseColor("#FF527AAA"), parseColor("#FF20344A")),
            intArrayOf(parseColor("#FF3392B1"), parseColor("#FF1B2A65")),
            intArrayOf(parseColor("#FF212B4F"), parseColor("#FF131E3A")),
            intArrayOf(parseColor("#FF2d4383"), parseColor("#FFae4aa0")),
            intArrayOf(parseColor("#FF9fb0cc"), parseColor("#FF121c33")),
            intArrayOf(parseColor("#FF030B26"), parseColor("#FF463959")),
            intArrayOf(parseColor("#FF608396"), parseColor("#FFf88063")),
            intArrayOf(parseColor("#FF554686"), parseColor("#FF6e51c9")),
            intArrayOf(parseColor("#FFf0a87f"), parseColor("#FF415262")),
            intArrayOf(parseColor("#FFFFEC84"), parseColor("#FFFF8B88")),
            intArrayOf(parseColor("#FF225664"), parseColor("#FF65CBBF")),
            intArrayOf(parseColor("#FF35556f"), parseColor("#FF5492c2"))
    )

    private fun parseColor(value: String): Int {
        return Color.parseColor(value)
    }
}
